authapi:
  build: .
  dockerfile: Dockerfile.alpine
  command: ./run.sh
  environment:
    - PORT=5000
  ports:
  - 5000:5000

master:
  image: kontena/server
  environment:
    - RACK_ENV=production
    - MONGODB_URI=mongodb://mongodb:27017/kontena_development
    - AUTH_API_URL=http://authapi:5000
  links:
  - mongodb
  - authapi
  ports:
  - 4040:9292

mongodb:
  image: mongo:2.8
  command: mongod --smallfiles
